export {
  STAGE_CHECKLIST,
  STAGE_GROUPS,
  belongsToProject,
  buildProjectStages,
  completedStageCount,
  currentStageLabel,
  emptyStageMap,
  emptyStatusFacts,
  evaluateProjectStages,
  fullLoopCtaNote,
  getProjectNextAction,
  groupProgress,
  markCurrentStages,
  mountWriteOperations,
  nextActionSkipsScript,
  performanceStageLabel,
  stageCountLabel,
  statusUnavailableLabel,
  usesPercentage,
  type ProjectNextAction,
  type ProjectOverviewSummary,
  type ProjectStageKey,
  type ProjectStageMap,
  type ProjectStatusFacts,
  type StageMark,
} from "./project-status";

export type StageKey = import("./project-status").ProjectStageKey;
