export const EDITORIAL_PREVIEW_RENDER_CONFIG = {
  reviewWidth: 720,
  reviewHeight: 1280,
  productionWidth: 1080,
  productionHeight: 1920,
  codec: 'libx264',
  pixelFormat: 'yuv420p',
  crf: 20,
  preset: 'medium',
  scaler: 'lanczos',
  fps: 30,
  audioPolicy: 'MUTE_SOURCE_AUDIO' as const,
  productionUsable: false as const,
  previewUpscaleAllowed: false as const,
  productionSourcePolicy: 'DIRECT_FROM_ORIGINAL_SOURCE' as const,
  previewVersion: 'editorial-preview:runtime-1',
  planVersion: 'editorial.shot-plan:v1',
  timeoutMs: 300_000,
  blurLuma: 20,
  blurChroma: 20,
  wideBgBrightness: -0.22,
  mediumBgBrightness: -0.12,
  mediumOverlay: 0.84,
  easedMotionMs: 400,
  easedZoomEnd: 1.06,
  maxEasedShots: 2,
} as const;

export const EDITORIAL_UAT_CHECKLIST = [
  'SHOT_HIERARCHY_ACCEPTABLE',
  'WIDE_CONTEXT_EFFECTIVE',
  'MEDIUM_FOCUS_EFFECTIVE',
  'DETAIL_USED_ONLY_WHEN_NEEDED',
  'NARRATION_VISUAL_ALIGNMENT_ACCEPTABLE',
  'CONTEXT_RECOVERY_ACCEPTABLE',
  'BACKGROUND_COMPOSITION_ACCEPTABLE',
  'MOBILE_READABILITY_ACCEPTABLE',
  'TRANSITIONS_NATURAL',
  'TRUTH_PRESERVED',
] as const;
