export const MARKET_EVIDENCE_VERSION = 'v1' as const;

export const MARKET_EVIDENCE_MAX_JSON_BYTES = 16 * 1024;

export const MARKET_EVIDENCE_LIMITS = {
  keywordEvidence: 10,
  contentEvidence: 10,
  competitorEvidence: 8,
  trendEvidence: 8,
  audienceEvidence: 8,
  opportunityEvidence: 8,
  contentKeys: 5,
  keywordKeys: 5,
  competitorKeys: 5,
  trendKeys: 5,
  audienceKeys: 5,
  examples: 2,
  topN: 5,
} as const;

export const MARKET_EVIDENCE_MIN_CONTENT_FOR_PATTERN = 5;
export const MARKET_EVIDENCE_MIN_FREQUENCY = 2;

export const MARKET_EVIDENCE_DURATION_BUCKETS = {
  SHORT_MAX: 30,
  MEDIUM_MAX: 60,
} as const;

export const MARKET_EVIDENCE_DURATION_LABELS = ['SHORT', 'MEDIUM', 'LONG'] as const;

export const MARKET_EVIDENCE_CODES = [
  'INSUFFICIENT_DATA',
  'KEYWORD_SAMPLE_SIZE',
  'TOP_REPEATED_RELATED_KEYWORDS',
  'SEARCH_RANK_PRESENT',
  'VOLUME_SIGNAL_DISTRIBUTION',
  'COMPETITION_SIGNAL_DISTRIBUTION',
  'HIGH_VOLUME_SIGNAL_KEYWORDS',
  'HIGH_COMPETITION_SIGNAL_KEYWORDS',
  'LOW_COMPETITION_SIGNAL_KEYWORDS',
  'CONTENT_SAMPLE_SIZE',
  'SAMPLE_MEDIANS',
  'MISSING_CONTENT_METRICS',
  'ABOVE_SAMPLE_MEDIAN_VIEWS',
  'ABOVE_SAMPLE_MEDIAN_ENGAGEMENT',
  'TOP_SAMPLE_VIEWS_CONTENT',
  'TOP_SAMPLE_ENGAGEMENT_CONTENT',
  'HASHTAG_FREQUENCY',
  'CONTENT_KEYWORD_FREQUENCY',
  'AUTHOR_FREQUENCY',
  'DURATION_BUCKET_DISTRIBUTION',
  'COMPETITOR_SAMPLE_SIZE',
  'FOLLOWER_COUNT_DISTRIBUTION',
  'RECENT_POST_COUNT_DISTRIBUTION',
  'POSTING_FREQUENCY_SIGNAL_DISTRIBUTION',
  'ENGAGEMENT_SIGNAL_DISTRIBUTION',
  'CONTENT_THEME_FREQUENCY',
  'TOP_FOLLOWER_COUNT_IN_SAMPLE',
  'WEAK_COMPETITOR_IDENTITY_COUNT',
  'TREND_SAMPLE_SIZE',
  'TOP_RANKED_TRENDS',
  'HEAT_SIGNAL_DISTRIBUTION',
  'TREND_CATEGORY_FREQUENCY',
  'AUDIENCE_SIGNAL_SAMPLE_SIZE',
  'TOP_REPEATED_TOPICS',
  'SIGNAL_TYPE_DISTRIBUTION',
  'FREQUENCY_RANKING',
  'PRODUCT_MARKET_KEYWORD_OVERLAP',
  'LOW_SAMPLE_COVERAGE_FOR_SELLING_POINT',
  'HIGH_VOLUME_LOW_COMPETITION_SIGNAL',
] as const;

export type MarketEvidenceCode = (typeof MARKET_EVIDENCE_CODES)[number];

export const MARKET_EVIDENCE_FLAGS = [
  'NO_DATA',
  'LIMITED_DATA',
  'MANUAL_ONLY',
  'IMPORT_ONLY',
  'MISSING_METRICS',
  'WEAK_IDENTITIES',
  'SMALL_CONTENT_SAMPLE',
  'SMALL_KEYWORD_SAMPLE',
  'COLLECTED_AT_ASSUMED',
  'UNKNOWN_SELECTION_METHOD',
] as const;

export type MarketEvidenceFlag = (typeof MARKET_EVIDENCE_FLAGS)[number];
