export const COMPARISON_THRESHOLDS = {
  labelHighMin: 0.8,
  labelMediumMin: 0.5,
  readabilityHighMin: 0.7,
  readabilityMediumMin: 0.45,
  dominanceDelta: 0.05,
  claimPreservedMin: 0.8,
  claimPartialMin: 0.5,
  temporalVarianceCap: 0.55,
  presentationPadPenalty: 0.15,
} as const;

export const COMPARISON_RULE_IDS = {
  ELIGIBILITY: 'RULE_DIRECTOR_ELIGIBILITY_FROM_B2_9_STATUS',
  UNSAFE_INELIGIBLE: 'RULE_UNSAFE_NEVER_DIRECTOR_ELIGIBLE',
  BLOCKED_NEVER: 'RULE_BLOCKED_NEVER_DIRECTOR_ELIGIBLE',
  NO_MUTATION: 'RULE_NO_CANDIDATE_MUTATION',
  WORST_FRAME: 'RULE_WORST_FRAME_EVIDENCE',
  READABILITY_PROXY: 'RULE_OCCUPANCY_READABILITY_PROXY',
  CHROME_EXCLUSION: 'RULE_BROWSER_EXCLUSION_SOFT_AXIS',
  TEMPORAL_CAP: 'RULE_TEMPORAL_VARIANCE_NOT_HIGH',
  CLAIM_C5_NA: 'RULE_C5_NOT_CLAIM_CRITICAL',
  CLAIM_C6_NA: 'RULE_C6_NOT_DEFAULT_CLAIM',
  HARD_OVER_PRESENTATION: 'RULE_PRESENTATION_CANNOT_DOMINATE_EVIDENCE',
  PARETO_NOT_WINNER: 'RULE_PARETO_IS_NOT_WINNER',
  NO_OVERALL_SCORE: 'RULE_NO_SINGLE_MAGIC_SCORE',
  CONTRACT_ELIGIBLE_ONLY: 'RULE_DIRECTOR_MUST_SELECT_ELIGIBLE',
  CONTRACT_RATIONALE: 'RULE_DIRECTOR_RATIONALE_REQUIRED',
  CONTRACT_NO_UNSAFE: 'RULE_DIRECTOR_CANNOT_SELECT_UNSAFE',
  CONTRACT_NO_BLOCKED: 'RULE_DIRECTOR_CANNOT_SELECT_BLOCKED',
  CONTRACT_KNOWN_ID: 'RULE_DIRECTOR_KNOWN_CANDIDATE_OR_REQUEST_NEW',
  HUMAN_REVIEW: 'RULE_HUMAN_REVIEW_ON_STATIC_WARNINGS',
  STATIC_DYNAMIC: 'RULE_STATIC_WITH_WARNINGS_NOT_DYNAMIC_REQUIRED',
  DISPLAY_ORDER: 'RULE_DISPLAY_ORDER_NOT_RANKING',
} as const;

export const HARD_RELEVANT_AXES = [
  'SAFETY',
  'KEY_EVIDENCE_PRESERVATION',
  'CLAIM_SUPPORT',
  'PRODUCT_UI_PRESERVATION',
  'NAVIGATION_PRESERVATION',
  'TEXT_PRESERVATION',
] as const;

export const COMPARISON_PRECEDENCE = [
  'HARD_BLOCK_SAFETY',
  'TRUTH_CLAIM_EVIDENCE',
  'KEY_EVIDENCE_PRESERVATION',
  'READABILITY',
  'TEMPORAL_STABILITY',
  'PRESENTATION_CLEANLINESS',
  'CREATIVE_PREFERENCE',
] as const;
