export const SOURCE_AWARE_PREVIEW_RENDER_CONFIG = {
  reviewWidth: 720,
  reviewHeight: 1280,
  productionWidth: 1080,
  productionHeight: 1920,
  landscapeProductionWidth: 1920,
  landscapeProductionHeight: 1080,
  verticalProfileId: 'production.vertical.douyin:v1',
  landscapeProfileId: 'production.landscape.ui-demo:v1',
  universalHardResolution: false as const,
  codec: 'libx264',
  pixelFormat: 'yuv420p',
  crf: 20,
  preset: 'medium',
  scaler: 'lanczos',
  fps: 30,
  audioPolicy: 'MUTE_SOURCE_AUDIO' as const,
  productionUsable: false as const,
  previewUpscaleAllowed: false as const,
  productionSourcePolicy: 'DIRECT_FROM_ORIGINAL_SOURCE' as const,
  previewVersion: 'source-aware-preview:runtime-1',
  planVersion: 'source-aware.editorial-director:v2',
  timeoutMs: 300_000,
  blurLuma: 20,
  blurChroma: 20,
  wideBgBrightness: -0.22,
} as const;

export const SOURCE_AWARE_UAT_CHECKLIST = [
  'WHOLE_UI_COMPOSITION_NATURAL',
  'NO_BROKEN_TEXT_OR_UI_CONTAINER',
  'BLANK_GAP_REMOVED',
  'SMART_UI_FIT_ACCEPTABLE',
  'BACKGROUND_FRAMING_ACCEPTABLE',
  'SOURCE_AWARE_DIRECTION_ACCEPTABLE',
  'MOBILE_VIEW_ACCEPTABLE',
  'REFRAME_ONLY_WHEN_USEFUL',
  'VISUAL_RHYTHM_ACCEPTABLE',
  'TRUTH_PRESERVED',
] as const;
