export const SEMANTIC_FRAME_ERROR = {
  SEMANTIC_FRAME_SELECTION_FAILED: 'SEMANTIC_FRAME_SELECTION_FAILED',
  SEMANTIC_FRAME_EXTRACTION_FAILED: 'SEMANTIC_FRAME_EXTRACTION_FAILED',
  SEMANTIC_FRAME_DECODE_FAILED: 'SEMANTIC_FRAME_DECODE_FAILED',
  SEMANTIC_FRAME_TIMEOUT: 'SEMANTIC_FRAME_TIMEOUT',
  SEMANTIC_FRAME_INVALID_OUTPUT: 'SEMANTIC_FRAME_INVALID_OUTPUT',
  SEMANTIC_FRAME_INSUFFICIENT: 'SEMANTIC_FRAME_INSUFFICIENT',
  SEMANTIC_FRAME_PARTIAL: 'SEMANTIC_FRAME_PARTIAL',
  SEMANTIC_FRAME_INVALID_TIMESTAMP: 'SEMANTIC_FRAME_INVALID_TIMESTAMP',
} as const;

export type SemanticFrameErrorCode = (typeof SEMANTIC_FRAME_ERROR)[keyof typeof SEMANTIC_FRAME_ERROR];

export const SEMANTIC_FRAME_WARNING = {
  SEMANTIC_FRAME_DEDUPED: 'SEMANTIC_FRAME_DEDUPED',
  SEMANTIC_FRAME_RETRY_OFFSET: 'SEMANTIC_FRAME_RETRY_OFFSET',
  SEMANTIC_FRAME_LOW_SHARPNESS_HINT: 'SEMANTIC_FRAME_LOW_SHARPNESS_HINT',
  SEMANTIC_FRAME_DARK_HINT: 'SEMANTIC_FRAME_DARK_HINT',
  SEMANTIC_FRAME_BUDGET_TRIMMED: 'SEMANTIC_FRAME_BUDGET_TRIMMED',
  SEMANTIC_FRAME_SPARSE_B1_FALLBACK: 'SEMANTIC_FRAME_SPARSE_B1_FALLBACK',
  SEMANTIC_FRAME_USED_SAMPLE_TIMESTAMPS: 'SEMANTIC_FRAME_USED_SAMPLE_TIMESTAMPS',
} as const;

export type SemanticFrameWarningCode = (typeof SEMANTIC_FRAME_WARNING)[keyof typeof SEMANTIC_FRAME_WARNING];
