export const COMPOSITION_STAGE = Symbol('COMPOSITION_STAGE');
export const VISUAL_GENERATION_STAGE = Symbol('VISUAL_GENERATION_STAGE');
export const VOICE_GENERATION_STAGE = Symbol('VOICE_GENERATION_STAGE');
export const SUBTITLE_GENERATION_STAGE = Symbol('SUBTITLE_GENERATION_STAGE');
