import type { CropThresholdConfigV1 } from './crop-candidate.types.js';

/** Engineering thresholds — not a product SLA. */
export const CROP_SAFETY_THRESHOLDS: CropThresholdConfigV1 = {
  mustKeepMin: 0.95,
  shouldKeepMin: 0.8,
  productUiEnvelopeMin: 0.35,
  claimCriticalMin: 0.9,
  claimCriticalSevereMax: 0.5,
  textCriticalMin: 0.9,
  textNormalMin: 0.75,
  browserChromePreferredMax: 0.25,
  hardExcludeMaxIncluded: 0.05,
  occupancyReadabilityWarnMax: 0.4,
  retainedAreaEvidenceWarnMax: 0.4,
  iouDedupMin: 0.95,
  maxCandidates: 8,
};

export const RULE_IDS = {
  MUST_KEEP_COVERAGE: 'RULE_MUST_KEEP_COVERAGE',
  HARD_EXCLUDE_INCLUDED: 'RULE_HARD_EXCLUDE_INCLUDED',
  SHOULD_KEEP_COVERAGE: 'RULE_SHOULD_KEEP_COVERAGE',
  PRODUCT_UI_ENVELOPE: 'RULE_PRODUCT_UI_ENVELOPE_NOT_WHOLE_SURFACE',
  CHILD_REGION_PRIORITY: 'RULE_CHILD_REGION_PRIORITY',
  CLAIM_CRITICAL_COVERAGE: 'RULE_CLAIM_CRITICAL_COVERAGE',
  C5_NOT_CLAIM_CRITICAL: 'RULE_C5_NOT_CLAIM_CRITICAL_MUST_KEEP',
  TEXT_CUTOFF: 'RULE_TEXT_PARTIAL_CUT',
  BROWSER_PREFER_EXCLUDE: 'RULE_BROWSER_CHROME_SOFT_PREFER_EXCLUDE',
  LOCALHOST_SOFT: 'RULE_LOCALHOST_INCLUDED_SOFT',
  CENTER_COVER_EVIDENCE: 'RULE_CENTER_COVER_EVIDENCE_LOSS',
  CONTAIN_OCCUPANCY: 'RULE_CONTAIN_OCCUPANCY_READABILITY',
  ASSET_USAGE_BLOCK: 'RULE_BLOCKED_ASSET_NO_PRODUCTION_CANDIDATES',
  NO_STRETCH: 'RULE_NO_NON_UNIFORM_STRETCH',
  ASPECT_EXPAND_FIRST: 'RULE_ASPECT_PREFER_EXPAND',
  NO_BLIND_CENTER: 'RULE_NO_BLIND_SOURCE_MIDPOINT',
  SAMPLED_PRECISION: 'RULE_SAFETY_PRECISION_SAMPLED',
  WORST_FRAME: 'RULE_WORST_FRAME_SAFETY',
  DEDUP: 'RULE_CANDIDATE_IOU_DEDUP',
  BUDGET: 'RULE_MAX_CANDIDATES_8',
  INVALID_RECT: 'RULE_NO_SILENT_CLAMP',
  TOP_TRIM_FROM_CHROME: 'RULE_TOP_TRIM_USES_OBSERVED_CHROME',
  STATIC_ASSESSMENT: 'RULE_STATIC_CROP_WORST_FRAME',
} as const;
