export const FRAME_ANALYSIS_ERROR = {
  FRAME_EXTRACTION_FAILED: 'FRAME_EXTRACTION_FAILED',
  FRAME_DECODE_FAILED: 'FRAME_DECODE_FAILED',
  FRAME_STATS_FAILED: 'FRAME_STATS_FAILED',
  FRAME_SAMPLING_SKIPPED_DURATION_UNKNOWN: 'FRAME_SAMPLING_SKIPPED_DURATION_UNKNOWN',
  NO_USABLE_FRAME_SAMPLE: 'NO_USABLE_FRAME_SAMPLE',
} as const;

export type FrameAnalysisErrorCode = (typeof FRAME_ANALYSIS_ERROR)[keyof typeof FRAME_ANALYSIS_ERROR];
